openapi: 3.0.0
info:
  title: Sample API
  description: API for RecipeProvider
  version: 0.1.9
servers:
  - url: http://localhost:8080
    description: Optional server description, e.g. Main (production) server

paths:
  /recipes:
    get:
      summary: Returns a list of recipes.
      description: Returns a list of recipes.
      operationId: getRecipes
      responses:
        '200':    # status code
          description: A JSON array of recipes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipeReadDto'
    post:
      summary: Create a recipe.
      description: Create a recipe.
      operationId: createRecipe
      requestBody:
        description: Created recipe in JSON format.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecipeWriteDto'
      responses:
        '200':
          description: callback successfully processed
components:
  schemas:
    RecipeReadDto:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
            format: uuid
          title:
            type: string
          ingredients:
            type: array
            items:
              type: string
          preparation:
            type: array
            items:
              type: string
    RecipeWriteDto:
      type: object
      properties:
        title:
          type: string
        ingredients:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              persons:
                type: object
                properties:
                  count:
                    type: object
                    properties:
                      amount:
                        type: string





