openapi: 3.0.0
info:
  title: Sample API
  description: API for RecipeProvider
  version: 0.1.9
servers:
  - url: http://localhost:8080
    description: Optional server description, e.g. Main (production) server

paths:
  /recipes:
    get:
      summary: Return a random recipe.
      description: Return a random recipe.
      operationId: getRandomRecipe
      responses:
        '200':    # status code
          description: Return a random recipe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipeReadDto'
    post:
      summary: Create a recipe.
      description: Create a recipe.
      operationId: createRecipe
      requestBody:
        description: Recipe in JSON format.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecipeWriteDto'
      responses:
        '200':
          description: callback successfully processed
components:
  schemas:
    RecipeReadDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        ingredients:
          type: array
          items:
            type: string
        preparation:
          type: array
          items:
            type: string
    RecipeWriteDto:
      type: object
      properties:
        title:
          type: string
        ingredients:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              persons:
                type: object
                additionalProperties:
                    type: object
                    properties:
                      amount:
                        type: string
        preparation:
          type: array
          items:
            type: string


